apt install python3
apt install pip3
pip3 install flask
pip3 install requests
pip3 install render_template
pip3 install url_for
pip3 install flash
pip3 install redirect
pip3 install flask_sqlalchemy
pip3 install requests
pip3 install json
